name: Echo Hello World

on:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      # Print Hello World to the console
      - name: Echo Hello World
        run: echo "Hello World"