name: Deployment_Pipeline_Example_App

on:
  workflow_dispatch:

jobs:
  Development:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      # Print Hello World to the console
      - name: Echo Hello World
        run: |
            echo $SECRET_STUFF
            echo $SECRET_REPO
            export test=$SECRET_STUFF
            export test2=$SECRET_REPO
            echo $test
            echo $test2
        env:
          SECRET_STUFF: ${{ secrets.SUPER_SECRET }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}

  Test:
    runs-on: ubuntu-latest
    needs: Development
    environment: TST
    steps:
      # Print Hello World to the console
      - name: Echo Hello World
        run: echo "Hello World"

  Acceptance:
    runs-on: ubuntu-latest
    needs: Test
    environment: ACC
    steps:
      # Print Hello World to the console
      - name: Echo Hello World
        run: echo "Hello World"

  Production:
    runs-on: ubuntu-latest
    needs: Acceptance
    environment: PRD
    steps:
      # Print Hello World to the console
      - name: Echo Hello World
        run: echo "Hello World"